import 'package:json_annotation/json_annotation.dart';

part 'message_response.g.dart'; // This file will be generated by build_runner

@JsonSerializable()
class MessageResponse {
  final String status;
  final Map<String, dynamic>? result;
  final String? error;

  MessageResponse(this.status, this.result, this.error);

  // From JSON
  factory MessageResponse.fromJson(Map<String, dynamic> json) => _$MessageResponseFromJson(json);

  // To JSON
  Map<String, dynamic> toJson() => _$MessageResponseToJson(this);
}