name: proyect_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  serverpod: 2.0.2
  serverpod_serialization: 2.0.2
  bcrypt: ^1.1.3
  envied: ^0.5.4+1
  serverpod_auth_server: 2.0.2
  http: ^1.2.2
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  proyect_shared_sergio:
    path: ../proyect_shared_sergio
  proyect_shared_santiago:
    path: ../proyect_shared_santiago

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  lints: '>=3.0.0 <5.0.0'