name: proyect_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  serverpod: 2.0.2
  serverpod_serialization: 2.0.2
  bcrypt: ^1.1.3
  envied: ^0.5.4+1
  serverpod_auth_server: 2.0.2

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  lints: '>=3.0.0 <5.0.0'
