import 'package:json_annotation/json_annotation.dart';

part 'message_response.g.dart'; // This file will be generated by build_runner

// MessageRespose will let us work with the server response from the Afilnet API
@JsonSerializable()
class MessageResponse {
  final String status;
  // Result will change depending on the method used.
  final Map<String, dynamic>? result;
  final String? error;

  MessageResponse(this.status, this.result, this.error);
  
  // From JSON
  factory MessageResponse.fromJson(Map<String, dynamic> json) => _$MessageResponseFromJson(json);

  // To JSON
  Map<String, dynamic> toJson() => _$MessageResponseToJson(this);
}