type: server

client_package_path: ../proyect_client

modules:
  serverpod_auth:
    nickname: auth

extraClasses:
  - package:proyect_shared_sergio/proyect_shared_sergio.dart:GenericApiRequest
  - package:proyect_shared_sergio/proyect_shared_sergio.dart:GenericApiResponse
  - package:proyect_shared_santiago/proyect_shared_santiago.dart:MessageResponse
